export const FETCH_ERROR = 'FETCH_ERROR';
export const FETCH_PENDING = 'FETCH_PENDING';
export const FETCH_COMPANIES = 'FETCH_COMPANIES';

export const SELECTED_COMPANY = 'SELECTED_COMPANY';
export const SELECTED_COMPANY_PENDING = 'SELECTED_COMPANY_PENDING';
export const SELECTED_COMPANY_ERROR = 'SELECTED_COMPANY_ERROR';


export const FETCH_NEWS = 'FETCH_NEWS';
export const FETCH_NEWS_PENDING = 'FETCH_NEWS_PENDING';
export const FETCH_NEWS_ERROR = 'FETCH_NEWS_ERROR';

export const SEARCH_COMPANY = 'SEARCH_COMPANY';
export const SEARCH_COMPANY_PENDING = 'SEARCH_COMPANY_PENDING';
export const SEARCH_COMPANY_ERROR = 'SEARCH_COMPANY_ERROR';

export const CREATE_COMMENT = 'CREATE_COMMENT';
