export const FETCH_ERROR = 'FETCH_ERROR';
export const FETCH_PENDING = 'FETCH_PENDING';
export const FETCH_COMPANIES = 'FETCH_COMPANIES';
export const SELECTED_COMPANY = 'SELECTED_COMPANY';

export const CREATE_COMMENT = 'CREATE_COMMENT';
export const FETCH_NEWS = 'FETCH_NEWS';
