export const FETCH_COMPANIES = 'FETCH_COMPANIES';
export const FETCH_COMPANIES_PENDING = 'FETCH_COMPANIES_PENDING';
export const FETCH_COMPANIES_ERROR = 'FETCH_COMPANIES_ERROR';
export const SELECTED_COMPANY = 'SELECTED_COMPANY';


export const CREATE_COMMENT = 'CREATE_COMMENT';
